api:
    entities:
#        Oro\Bundle\CalendarBundle\Entity\Calendar:
#            actions:
#                delete:
#                    acl_resource: oro_calendar_view
#                delete_list:
#                    acl_resource: oro_calendar_view
#
#        Oro\Bundle\CalendarBundle\Entity\CalendarEvent:
#            delete_handler: oro_calendar.calendar_event.handler.delete
#            fields:
#               activityTargets:
#                   description: A records to which the Calendar event record associated with
#                   data_type: association:manyToMany:activity
#            filters:
#                fields:
#                    updatedAt: ~ # enable manually because this field is not indexed
#            subresources:
#                activityTargets:
#                    actions:
#                        get_subresource:
#                            documentation: Get full information about records to which the calendar event associated
#                        get_relationship:
#                            documentation: Get records to which the calendar event associated
#                        add_relationship:
#                            documentation: Associate records with the calendar event
#                        update_relationship:
#                            documentation: Completely replace association between records and the calendar event
#                        delete_relationship:
#                            documentation: Delete association between records and the calendar event
#
#        Oro\Bundle\CalendarBundle\Entity\CalendarProperty: ~
#
#        Oro\Bundle\CalendarBundle\Entity\SystemCalendar:
#            delete_handler: oro_calendar.system_calendar.handler.delete
#            actions:
#                delete:
#                    acl_resource: ~
#                delete_list:
#                    acl_resource: ~

        # remove these exclusions when calendar entities will be enabled for Data API
        Extend\Entity\EV_Ce_Attendee_Status: { exclude: true}
        Extend\Entity\EV_Ce_Attendee_Type: { exclude: true}
